name: Daily Maestro Test

on:
  workflow_dispatch:

  schedule:
    - cron: '30 2 * * *'   # 8:00 AM IST

jobs:
  maestro-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: pixel_6
          script: |
            adb devices

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          export PATH="$PATH":"$HOME/.maestro/bin"
          maestro --version

      - name: Install APK
        run: |
          adb install "apk/release-1.5.7(60).apk"

      - name: Run Maestro Flow
        run: |
          export PATH="$PATH":"$HOME/.maestro/bin"
          maestro test .maestro/Login_click_on_Hindi.yaml
