name: Daily Maestro Test

on:
  workflow_dispatch:

jobs:
  maestro-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Run Emulator and Maestro
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: pixel_6
          script: |
            adb devices

            adb install "apk/release-1.5.7(60).apk"

            maestro test .maestro/Login_click_on_Hindi.yaml
